kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: topic-01
  labels:
    strimzi.io/cluster: poc-01
  namespace: kafka
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
